Bills branch
IEEEBerkeley/ieee-ghost pull request #17
Opened 2020-09-27 14:33 UTC by DarKnight0102

add officer card

2020-09-27 17:54 UTC, PotatoParser requested changes
Looks very good!

2020-09-27 17:54 UTC, PotatoParser commented on page-officers.hbs
> +                  <img src="{{asset 'officers/Website/bill_hu.png'}}" alt="profilepic"/>
The file you added was a `.jpg`, not a `.png`

2020-09-27 20:24 UTC, PotatoParser approved these changes
Looks good now!

2020-09-28 19:14 UTC, encadyma approved these changes
Looks great!

2020-09-28 19:15 UTC, merged