kyle first pull request
IEEEBerkeley/ieee-ghost pull request #27
Opened 2020-10-03 18:43 UTC by imkyleyu

2020-10-03 19:37 UTC, PotatoParser requested changes
Looks good! Please take a look at #23 and fix your profile accordingly.

2020-10-03 22:45 UTC, PotatoParser requested changes
Looks good, just a slight correction is needed.

2020-10-03 22:45 UTC, PotatoParser commented on page-officers.hbs
> +                  <img src="{{asset 'officers/Website/kyle_yu.png'}}" alt="profilepic"/>
The url needs changing here

2020-10-03 22:50 UTC, imkyleyu commented on page-officers.hbs
> +                  <img src="{{asset 'officers/Website/kyle_yu.png'}}" alt="profilepic"/>
Oops... sorry about that.

2020-10-04 01:06 UTC, PotatoParser approved these changes
Great!

2020-10-04 09:39 UTC, merged