Create footer
IEEEBerkeley/ieee-ghost pull request #4
Opened 2020-05-19 07:46 UTC by andrewkdinh

Replicated this mockup footer

<img width="1332" alt="footer" src="https://user-images.githubusercontent.com/45807756/82299133-ab8c3400-99a4-11ea-8abb-ff34bc70ef80.png">

2020-05-19 19:18 UTC, PotatoParser requested changes
Overall a very clean job! There are just a few visual elements that are off.

2020-05-19 19:18 UTC, PotatoParser commented on partials/footer.hbs
> +          <li><a href="apply" rel="noopener">Apply</a></li>
Switch href to absolute path: `{{ @site.url }}/<route to your link>`

2020-05-19 19:18 UTC, PotatoParser commented on partials/footer.hbs
> +          <li><a href="industry" rel="noopener">Industrial Relations</a></li>
Switch href to absolute path: `{{ @site.url }}/<route to your link>`

2020-05-19 19:18 UTC, PotatoParser commented on src/sass/components/_footer.scss
> +  background-color: transparent;
Add `border-style: solid;` instead of using the default of `outset`

2020-05-19 19:18 UTC, PotatoParser commented on partials/footer.hbs
> +    <p>{{@site.title}} &copy; {{date format="YYYY"}}</p>
I'm not sure if this is the correct copyright that we want to see. I think the site title is different from our actual copyright. `© Copyright 2020 IEEE Student Branch at UC Berkeley`

2020-05-19 19:18 UTC, PotatoParser commented on src/sass/components/_footer.scss
> +  color: rgba(253, 180, 21);
This color is a little warm, the hexcode for the color in the image is `#fed966`

2020-05-19 19:18 UTC, PotatoParser commented on src/sass/components/_footer.scss
> +.footer-col a {
Needed hover animation (to help users see what they are hovering over)

2020-05-19 19:18 UTC, PotatoParser commented on src/sass/components/_footer.scss
> +.footer-mailing-list button {
There seems to be a small border-radius on the image, perhaps adding `border-radius: 2px;` would work.

2020-05-19 23:05 UTC, encadyma approved these changes
Any reason why the mailing list border is outsetted? Otherwise, it looks good.

2020-05-19 23:57 UTC, sulattphone approved these changes
Looks solid.
I wonder how it would look if we have our IEEE logo right in the middle of the footer? Can we see that?

2020-05-20 01:01 UTC, andrewkdinh commented
> Any reason why the mailing list border is outsetted? Otherwise, it looks good.

What do you mean it’s outsetted?

2020-05-20 01:03 UTC, PotatoParser commented
@andrewkdinh Don't worry! You resolved the issue in your latest commit!

2020-05-20 03:33 UTC, andrewkdinh commented
@sulattphone I added the IEEE logo to the footer but made it disappear for smaller devices because it felt too cluttered

<img width="1439" alt="Screen Shot 2020-05-19 at 8 33 00 PM" src="https://user-images.githubusercontent.com/45807756/82401917-a5509300-9a4a-11ea-9f2e-01b96377646e.png">

2020-05-21 00:09 UTC, sulattphone commented
> @sulattphone I added the IEEE logo to the footer but made it disappear for smaller devices because it felt too cluttered
> 
> <img alt="Screen Shot 2020-05-19 at 8 33 00 PM" width="1439" src="https://user-images.githubusercontent.com/45807756/82401917-a5509300-9a4a-11ea-9f2e-01b96377646e.png">

Oh I love this actually. Yeah I agree that it would be too much for the mobile screens. Alright we can discuss more about all these designs at the meeting.

2020-05-23 01:46 UTC, closed without merging